server:
  port: 8110 # 服务端口
  tomcat:
    max-threads: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///guli?serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  redis:
#    host: 192.168.100.100
#    port: 6379
#    database: 0
#    password: 123456 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
#    spring:
#      cloud:
#    sentinel:
#      transport:
#        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
#        dashboard: localhost:8080 # 指定控制台服务的地址


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    root: info

#service-product: # 调用的提供者的名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true